variables:
  DOCKER_DRIVER: overlay2
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - docker
  - build
  - screenshot

docker:build:
  stage: docker
  image: docker:latest
  services:
    - docker:dind
  only:
    changes:
      - Dockerfile.build
      - tools/install-android-tools.sh
      - tools/install-debian-packages.sh
  before_script:
    - docker info
  script:
    - sh tools/build_and_push_from_docker_file.sh build
  except:
    - schedules

docker:screenshot:
  stage: docker
  image: docker:latest
  services:
    - docker:dind
  only:
    changes:
      - Dockerfile.screenshot
  before_script:
    - docker info
  script:
    - sh tools/build_and_push_from_docker_file.sh screenshot
  except:
    - schedules

build:unix:
  stage: build
  image:
    name: "registry.gitlab.com/roeles/xcsoar/build"
  script:
    - make WERROR=n OPENGL=n ENABLE_SDL=y FREETYPE=y
  artifacts:
    paths:
      - output/UNIX/bin/xcsoar

build:android:
  stage: build
  image:
    name: "registry.gitlab.com/roeles/xcsoar/build"
  script:
    - make TARGET=ANDROID7 DEBUG=n
  artifacts:
    paths:
      - output/ANDROID7/bin/XCSoar-debug.apk
    expire_in: 1 week

build:openvario:
  stage: build
  trigger: roeles/openvario_docker
  only:
    refs:
      - zen-krt2-pathfinder

pathfinder:
  stage: screenshot
  needs: ["build:unix"]
  image:
    name: "registry.gitlab.com/roeles/xcsoar/screenshot"
  script:
    - export DISPLAY=:0
    - Xvfb $DISPLAY &
    - ./output/UNIX/bin/xcsoar -fly -1280x1024 &
    - sleep 1m
    - import -window root screenshot.png
  artifacts:
    paths:
      - screenshot.png
    expire_in: 1 day
