FROM debian:buster
RUN apt-get update && apt-get install -y -qq --no-install-recommends xvfb imagemagick libasound2 liblua5.2-0 libcurl4 libgeotiff2 libsdl2-2.0-0 fonts-dejavu && apt-get clean
ENTRYPOINT /bin/bash
